apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
   - name: mysql-pass
     literals:
          - password=redhat
resources:
       - pk-efs-provisioner.yaml
       - pk-rbac.yaml
       - pk-storage-class.yaml
       - pk-deploy-mysql.yaml
       - pk-deploy-joomla.yaml
