apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
   - name: mysql-pass
     literals:
          - password=redhat
resources:
       - create_efs_provisioner.yaml
       - create_rbac.yaml
       - create_storage_class.yaml
       - create_sql_deployment.yaml
       - create_joomla_deployment.yaml
       
